### PR TITLE
Add testing suggestions to CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by karldw**
I ran into some issues when trying to run the tests, so I thought I would document them for other contributors.

### CODE REVIEW

**Comment by karldw** [comment]
Sure!  Do you want to suggest contributors run `devtools::test()`, or are the `check_*` functions enough?

**Comment by alexpghayes** [comment]
Contributors need to run `devtools::test()`. They need to pass `check_*` **in addition** to tests they write themselves.

In the near future `check_*` will become much more thorough and strict.

**Comment by karldw** [comment]
This is an ugly rebase. I have regrets.

**Comment by alexpghayes** [comment]
@karldw I'm not sure how to deal with the git situation here. Maybe a new PR??

**Comment by karldw** [comment]
Closed in favor of #397

**Pull request closed without merging**
