### PR TITLE
return tibbles for anova tidiers per #150

### PR DESCRIPTION
**Pull request by mkuehn10**
#150

### CODE REVIEW

**Comment by alexpghayes** [comment]
Hey @mkuehn10 this is awesome! If you're going to convert more tiddiers to tibbles, would you mind doing it all in the same pull request so I can add all the changes to master at once?

**Comment by mkuehn10** [comment]
Yes, sorry.  I wasn't sure if I should do that or not.  I was practicing making local branches and pushing them  and doing PRs. :)

**Comment by alexpghayes** [comment]
No need to be sorry! That's an great thing to be practicing!

**Comment by mkuehn10** [comment]
I'm not sure how to combine the last three branches I made in to one pull request.  I'm sure it's possible (but sounds scary), but I will have to research it.

**Comment by alexpghayes** [comment]
Oh don't worry about combining them! If you're going to add to stuff, do it here though.

**Comment by mkuehn10** [comment]
If/when I do more of making sure things output tibbles, I'll do them all together, but I was going to open up a new branch on my local machine called tibbles or something like that and keep all of them there and do a PR when I get a bunch of them.  Are you saying I should just use my `anova-tibbles` branch and keep adding to that?

**Comment by alexpghayes** [comment]
Either is fine. It's just good to group similar contributions together.

**Comment by alexpghayes** [comment]
Thanks again!

**Pull request merged**
