### PR TITLE
add labels to prcomp object before tidying

### LINKED ISSUE #254: integer labels for `tidy.prcomp()` when missing from `prcomp` object
Hi, i'm using **broom** with **tibble**, which discourages the use of row names, so that `tidy.prcomp` throws the error reproduced below. A simple fix was to assign the appropriate integer sequence to `labels`, which i've done at [this branch](/corybrunson/broom/tree/prcomp-labels). I didn't update documentation, but installing this change fixed my problem. I'm happy to send a PR but wanted to check first. (I couldn't find any discussion of this or reasons given not to.)

Thanks, both for any guidance and for the great package!

``` r
library(tibble)
library(broom)
test <- as.tibble(matrix(1:9, ncol = 3) + rnorm(n = 9, sd = 0.25))
test
#> # A tibble: 3 x 3
#>          V1       V2       V3
#>       <dbl>    <dbl>    <dbl>
#> 1 0.7009856 3.500583 6.987452
#> 2 2.1398779 5.031408 8.268146
#> 3 3.0907694 5.713359 8.464179
pca <- prcomp(test)
tidy(pca, matrix = "u")
#> Error in data.frame(label = rep(labels, times = ncomp), samples): arguments imply differing number of rows: 0, 9
rownames(test) <- 1:3
#> Warning: Setting row names on a tibble is deprecated.
pca <- prcomp(test)
tidy(pca, matrix = "u")
#>   row PC         value
#> 1   1  1 -2.006537e+00
#> 2   2  1  4.378777e-01
#> 3   3  1  1.568659e+00
#> 4   1  2  6.747315e-02
#> 5   2  2 -2.133301e-01
#> 6   3  2  1.458570e-01
#> 7   1  3  1.665335e-16
#> 8   2  3  2.220446e-16
#> 9   3  3  2.498002e-16
```

### PR DESCRIPTION
**Pull request by corybrunson**
This would fix #254 (see the discussion there for examples).

### CODE REVIEW

**Comment by alexpghayes** [comment]
If you pull in the most recent master the (AppVeyor) build should pass. It'd be nice to add a regression test and then I'd be happy to merge.

**Comment by corybrunson** [comment]
Thanks! I'm having some issues with the build (on a testing branch), but i'll push the merge and see what happens.

**Comment by alexpghayes** [comment]
Looks good. Would you add a quick test to make sure that the reprex from before:

```r
library(broom)
test <- as.data.frame(matrix(1:9, ncol = 3) + rnorm(n = 9, sd = 0.25))
test
#>          V1       V2       V3
#> 1 0.7707063 3.870905 7.091106
#> 2 2.3385348 4.987070 7.835155
#> 3 2.6638938 6.006691 8.690749
pca <- prcomp(test)
tidy(pca, matrix = "u")
#> Error in data.frame(label = rep(labels, times = ncomp), samples): arguments imply differing number of rows: 0, 9
test2 
```

doesn't give an error?

**Comment by corybrunson** [comment]
It works for me!

**Comment by corybrunson** [comment]
Or, did you mean add a test to some part of the PR?

**Comment by alexpghayes** [comment]
Yeah I meant add a test to the PR so that if the implementation gets changed in the future the error doesn't return.

**Comment by alexpghayes** [comment]
The test current checks that the original reprex fails. We should instead make sure that it passes. I think you want `expect_silent`, not `expect_error`. It's weird that that test passed.

**Comment by corybrunson** [comment]
The check uses `expect_error()` with `regexp = NA`, indicating that no error should occur, so it should pass. Is there something else wrong?

**Comment by alexpghayes** [comment]
Woops, my bad. That's it then. Feel free to add yourself as a contributor in DESCRIPTION!

**Pull request merged**
