### PR TITLE
tidy implementation for tseries::garch

### PR DESCRIPTION
**Pull request by wilsonfreitas**
The implementation of the tidy methods, tidy, glance and augment, for the garch class of tseries package.

### CODE REVIEW

**Comment by wilsonfreitas** [comment]
I am trying to run check but it is returning the following error

```
Error in UseMethod("as.quoted") : 
  no applicable method for 'as.quoted' applied to an object of class "quosures"
```

while evaluates the code below in `bootstraping.Rmd` vignette.

```r
ggplot(boot_coefs, aes(estimate)) + 
    geom_histogram(binwidth = 2) + 
    facet_wrap(facets = vars(term), scales = "free")
```

I guess it is being caused by `vars(term)` and I've already updated `rlang` (version 0.2.1).
I can't figure out what is going on.
any clue?

**Comment by alexpghayes** [comment]
It's building for me locally, and your AppVeyor build passed, which is promising. Maybe try updating your packages?

I just added a commit to use tidyverse style and return tibbles. If that passes the AppVeyor I'll merge. I also added you as a contributor.

**Comment by alexpghayes** [comment]
Thank you so much!

**Comment by wilsonfreitas** [comment]
Great @alexpghayes! This is awesome.

**Pull request merged**
