### PR TITLE
Random forest

### PR DESCRIPTION
**Pull request by mdlincoln**
Addresses half of #153 

Some notes:
## tidy

One row per model term, including the importance of each term (per class, when it is a classification RF) as measured by mean decrease in accuracy and mean decrease in the Gini index, along with standard errors of the importance measure.
## augment

One row per case, including the fitted value with a regression RF, forest votes in a classification RF, and casewise local importance of each model term when `localImp = TRUE` was called during the model building phase.
## glance

One row per model, with MSE and pseudo-Rsq for regression RF, class-wise precision/accuracy/recall/f_measure for classification RF. Note that I wasn't sure what, if anything, to implement here when the RF is running in unsupervised mode - I'm open to suggestions!
## R CMD check

~~I got a NOTE about a slow running test for `rstanarm_tidiers`, and a WARNING about a LaTeX error with the manual... though looking through the log I didn't see any errors thrown? Hopefully another pair of eyes may spot the issue.~~

Looks like it was just issues on my own machine. Though TravisCI seems to have it's own issues with all the other active PRs right now.

### CODE REVIEW

**Comment by mdlincoln** [comment]
FWIW #164 fixes the Travis CI build error showing up here.

**Comment by ismayc** [comment]
@mdlincoln Any updates here? Or are you thinking this would require other PRs to be merged? cc @rudeboybert

**Comment by mdlincoln** [comment]
I have... not changed anything in the past year, no 😂

**Comment by mdlincoln** [comment]
I've merged the latest updates into this PR, eliminating the merge conflict in DESCRIPTION.

**Comment by dgrtwo** [comment]
Thanks for this and sorry it's taken so long! I'm going to have to take a deeper look at the output before it goes into the CRAN release but really glad to have random forests incorporated

**Comment by dgrtwo** [comment]
Hi @mdlincoln!

I've been digging into the randomForest output a bit. Overall these are really important models to get tidied, but

1. I'm a bit concerned with the practice of having one column for each class (in augment) and one column for each term (in tidy/glance) since I'm not sure it's fully tidy (it stores data in column names). At the very least I think such output should be optional and default missing.

2. I have to submit the current version to CRAN (0.4.2 has been broken for a while), and I don't quite want to set in stone broom's tidied version of RFs (I'm worried once they get introduced they'll get some attention and excitement). So I'm temporarily removing rf_tidiers before submitting 0.4.3.

3. More important is that I've recently been planning a split of broom into a few related packages, with separate maintainers, to make management easier. I've wanted randomForest (as well as rpart and other tree-based methods) tidiers to live in a package called **broomstick**. @njtierney has volunteered to be a part of that and I'd like for you to be as well- these `rf_tidiers` will live there. Expect more news on that this week!

**Comment by talgalili** [comment]
FWISW I am very much waiting for the RF tidiers, and will probably play with them once they're out. <3

**Comment by njtierney** [comment]
:tada: I've just added some dormant commits here: https://github.com/njtierney/broomstick

**Comment by njtierney** [comment]
@mdlincoln let me know if you want to chat on video or something about moving forward from here.

**Comment by mdlincoln** [comment]
Hey @dgrtwo - yes, if you're going to maintain a separate package for trees, then these certainly belong over there!

Also, I agree that the tidying should not encode the categories in column names - it was my ill-thought-out attempt to conform to broom's general promise of "one line per model", which randomForest complicates a bit... I'll be very glad to adjust this code.

@njtierney I'm glad to port these over to broomstick, though I may not have bandwidth to do that until next month. I'll open up an issue over on broomstick in the meantime so that I have it on my to-do list, and can collate any questions there.

**Comment by njtierney** [comment]
@mdlincoln yup - I'll be a bit more free in the next month, that sounds good :)

**Pull request merged**
