### PR TITLE
augment method for chi-squared test

### PR DESCRIPTION
**Pull request by larmarange**
cf. https://github.com/dgrtwo/broom/issues/136

### CODE REVIEW

**Comment by benmarwick** [comment]
Thanks for proposing this, it would be an excellent addition to the package. It would  be a huge improvement over wrangling the output from `chisq.test` or `descr::CrossTable`. I hope this method can be added soon.

**Comment by alexpghayes** [comment]
If you're up for it amidst all the other `broom` work you're currently doing, I'd love to get this merged too!

**Comment by larmarange** [comment]
Dear @alexpghayes ,

I have rebased the pull request and I have tried to follow your vignette https://github.com/tidyverse/broom/blob/master/vignettes/adding-tidiers.Rmd

Some comments:

- I have applied `styler` only to the R files I have changed. But it seems that some other R files in `broom` do not respect `styler`. Maybe it could be relevant to clean the code and apply once `styler` to the overall package. By the way, it could be relevant to add a mention to `styler` package in your vignette.
- I have also run `goodpractice:gp()`  as requested but I have fixed only the comments relative to the R files I have amended. There is a lot of remarks regarding `broom` (mainly lines > 80 characters, the use of `sapply`, and the form `1:nrow(x)`). Maybe it would be relevant to clean a little the current code if you want to ask external contributors to use systematically `gp()`.
- It is not mentioned in your vignette if `NEWS.md` should be updated or not. I have updated it but let me know if it should not be part of the PR.
- When applying `pkgdown::build_site()` I encountered some errors and I have changed `_pkgdown.yml` to solve that problem (cf. https://github.com/tidyverse/broom/pull/138/commits/6a764dfb23bdc8dc766f92886ff83da66c791ebe) but let me know if it should be removed from the PR.
- In the vignette, it could be relevant to specify that for non US or UK developpers, it should be relevant to execute `Sys.setlocale("LC_ALL", "English")` before `pkgdown::build_site()`
- I have enclosed all changes due to `pkgdown::build_site()` in a separate commit although it was not specified in your vignette if you preferred a unique commit.
- You will see that the execution of `pkgdown::build_site()` is generating file conflicts. This is due to the fact that this command is updating all the website and therefore all pages (just because date as changed for example).  I do not know if it is a good idea to include `pkgdown::build_site()` in all PR as some conflicts could appear only because the website was updated since the PR was prepared. Maybe `devtools::document()` could be enough for a PR (as it will be enough for checking the package)?

Anyway, please let me known what are the changes you expect before an eventual integration of the PR. I prefer to finalise that one and to be sure to have understood all the elements you expect before preparing the other PR we discussed.

Best regards

**Comment by larmarange** [comment]
OK. 

I have rebased once again the PR from upstream/master and re-run `pkgdown::build_site()`

Let me know if any additional changes are required in the PR.

Regards

**Comment by alexpghayes** [comment]
Wow, this is fantastic feedback! I'll update the vignette on adding new tidiers later today -- thank you so much!

Everything you've done is totally reasonable. I'll try to get `styler` and `gp` cleaned up for the whole package, but it make take a little while.

**Comment by larmarange** [comment]
I completely understand.

Regarding the vignette (as I'm sure it will be a question for several occasional developers), it would be great if could specified:

- if you wants all the commits of the PR squashed into one or not;
- if you prefer `build_site` to be in a separate commit.

I do not know if it is important to explain all that process with the corresponding git commands. A link to https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request could be useful or a dedicated paragraph in the vignette.

Regards

**Pull request merged**
