### PR TITLE
Added basic glance and tidy for lavaan models.

### PR DESCRIPTION
**Pull request by puterleat**
nb. the op column is left in the tidy data frame for ease of sorting/filtering.
This addresses issue #27

### CODE REVIEW

**Comment by alexpghayes** [comment]
I'd love to get this merged in soon if you're still interested. If you are, can you:

- [ ]  Add tests for the methods you've implemented along the lines of those in `test-lm.R`. Ideal we're looking for fairly high coverage, with the tidiers tested for a decent variety of lavaan objects
- [ ] Make all of your methods return tibbles
- [ ] Add yourself as a contributor in DESCRIPTION

**Comment by benwhalley** [comment]
Cool. I've added some tests based on the `test-lm.R` file and amended the DESCRIPTION.
I have to admit, I don't fully understand the failures in Travis, which seem to be linked to rstanarm not installing. Do let me know if anything else is needed.

**Comment by alexpghayes** [comment]
Sorry for taking so long to get back to you. Thanks for adding the tests!

I've made a couple changes to align with current tidyverse style. These aren't fully documented at the moment, but we've started [here](http://broom.tidyverse.org/articles/adding-tidiers.html). Couple followup requests:

- The column names in `tidy` and `glance` output should be consistent with the rest of `broom`. Can you provide descriptions of the following so I can find the best match?
    - `aic   bic   cfi    chisq  logl  npar rmsea`
    - `std.lv std.all std.nox`
- The documentation should include examples of how use `tidy.lavaan` and `glance.lavaan`. It should also fully describe what each column in the output represents.
- For `glance` I think it would be better to remove the `fit.measures` argument and always return the largest reasonable set of measures of fit. Users can then later remove the ones they aren't interested in with `select`.

The Travis failures are currently on our end, we're currently only asking PRs to pass the AppVeyor build.

**Comment by benwhalley** [comment]
Just to respond inline below...

> The column names in tidy and glance output should be consistent with the rest of broom. Can you provide descriptions of the following so I can find the best match? aic bic cfi chisq logl npar rmsea

logl is log likelihood
chi2 is the chi squared — a measure of discrepancy between data and model fit
aic, bic are measures of fit based on information theory
npar is number of params in the model
rmsea is root mean squared error of approximation — another fit measure

std.lv std.all std.nox: these are all different types of standardised coefficient. That is, the params are standardised with respect to the latent variables only (std.lv) or all, or just excluding exogenous variables (nox)

On reflection I wonder if it would be better to offer this dataframe unstandaqdized by default, and in long form, with an additional `term` variable if the user requests standardised coefs?

> The documentation should include examples of how use tidy.lavaan and glance.lavaan. It should also fully describe what each column in the output represents.

I can add this

> For glance I think it would be better to remove the fit.measures argument and always return the largest reasonable set of measures of fit. Users can then later remove the ones they aren't interested in with select.

The most common case here, I think, is to want to compare models on various common fit indices, and perhaps also check the number of params. in the model, and the number of observations. On reflection, I think it might be best if I added the model N, and the estimator to this and always returned in long form. There's actually no point replicating lavaan::fitmeasures too closely... the trouble there is that one always has to subset the fitmeasures returned by default, and look elsewhere for the N and estimator.  I'll the another look

**Comment by alexpghayes** [comment]
Thanks! I'll probably change some of the `glance` column names up before the release for consistency with the rest of `broom`, but this looks great! I appreciate your contribution!

**Pull request merged**
