### PR TITLE
Methods for `survdiff` objects

### PR DESCRIPTION
**Pull request by mbojan**
As issue'd #145 . I have only ran tests in `test-survdiff.R`, mainly because of #146 .

### CODE REVIEW

**Comment by dgrtwo** [comment]
Nice, thank you!

I'll merge once you or I have finished out the TODO in the docs.

**Comment by mbojan** [comment]
Heh, sorry. I'll fix the TODOs. :) Developer's haste.

**Comment by mbojan** [comment]
Done. Seems to pass the check with `--no-tests` (for some reason I am not able to install `rstanarm`) and the tests in `test-survdiff.R`.

**Comment by mbojan** [comment]
I have rebased against current `master`. The CI seem to fail because of faulty examples of `tidy.orcutt`. Running `RCMD check` on my machine (skipping some of the dependencies) run OK.

**Pull request merged**
