### PR TITLE
pkgdown site for broom

### PR DESCRIPTION
**Pull request by jayhesselberth**
broom needs a pkgdown site!

Preview at https://vigilant-goldberg-0fd2e5.netlify.com/

- [ ] add the broom logo as `logo.png` in `man/figures` and re-run `pkgdown::build_site()`
- [ ] create `docs/CNAME` with single line containing`broom.tidyverse.org`
- [ ] In Settings / Github Pages / Source choose "master branch /docs folder"

The current Reference page has a lot of redundant entries because of the extensive use of S3 in broom (see https://github.com/hadley/pkgdown/issues/436).

### CODE REVIEW

**Comment by jayhesselberth** [comment]
closes #238

**Comment by topepo** [comment]
You might consider using [`DT`](https://rstudio.github.io/DT/) for the long table (or put it in an article)

**Comment by alexpghayes** [comment]
Thanks!

**Comment by alexpghayes** [comment]
@batpigandme I don't have access to the repo settings. Can you set up the Github pages?

**Comment by batpigandme** [comment]
@alexpghayes 10-4, I'm separated from my laptop rn, but I'll be on it once we're ruinited (my laptop and I) later tonight or AM. 👍

**Comment by batpigandme** [comment]
Oh, shoot do you mean on netlify, @alexpghayes? If so, I don't have access to that either…

**Comment by alexpghayes** [comment]
Thanks!

**Pull request merged**
